name: Deploy microservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure DNS
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf

      - name: Test Network Connectivity
        run: |
          curl -I https://adfvvcgbj.azurecr.io || echo "Failed to connect to container registry"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: ./scripts/build-image.sh

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: '1.24.2'
      
      - name: Deploy to Kubernetes
        run: ./scripts/deploy.sh
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Print Environment Variables
        run: |
          echo "CONTAINER_REGISTRY: $CONTAINER_REGISTRY"
          echo "VERSION: $VERSION"
          echo "REGISTRY_UN: $REGISTRY_UN"
          echo "REGISTRY_PW: $REGISTRY_PW"
