name: Deploy microservice

on:
  # Deploys the microservice on push to the main branch of this code repository.
  push:
    branches:
      - main

  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_UN }}
          password: ${{ secrets.REGISTRY_PW }}

      # Build the Docker image with Buildx
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY }}/my-image:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64

      # Install Kubectl and connect it to the cluster.
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      # Deploy the microservice
      - name: Deploy
        run: ./scripts/deploy.sh
